from setuptools import setup

setup(
    name='mse_teacher_plan',
    version='',
    packages=['app', 'venv.lib.python3.6.site-packages.bson', 'venv.lib.python3.6.site-packages.click',
              'venv.lib.python3.6.site-packages.flask', 'venv.lib.python3.6.site-packages.flask.json',
              'venv.lib.python3.6.site-packages.gridfs', 'venv.lib.python3.6.site-packages.jinja2',
              'venv.lib.python3.6.site-packages.blinker', 'venv.lib.python3.6.site-packages.pymongo',
              'venv.lib.python3.6.site-packages.visitor', 'venv.lib.python3.6.site-packages.wtforms',
              'venv.lib.python3.6.site-packages.wtforms.ext', 'venv.lib.python3.6.site-packages.wtforms.ext.csrf',
              'venv.lib.python3.6.site-packages.wtforms.ext.i18n',
              'venv.lib.python3.6.site-packages.wtforms.ext.django',
              'venv.lib.python3.6.site-packages.wtforms.ext.django.templatetags',
              'venv.lib.python3.6.site-packages.wtforms.ext.dateutil',
              'venv.lib.python3.6.site-packages.wtforms.ext.appengine',
              'venv.lib.python3.6.site-packages.wtforms.ext.sqlalchemy',
              'venv.lib.python3.6.site-packages.wtforms.csrf', 'venv.lib.python3.6.site-packages.wtforms.fields',
              'venv.lib.python3.6.site-packages.wtforms.widgets', 'venv.lib.python3.6.site-packages.dominate',
              'venv.lib.python3.6.site-packages.werkzeug', 'venv.lib.python3.6.site-packages.werkzeug.debug',
              'venv.lib.python3.6.site-packages.werkzeug.contrib', 'venv.lib.python3.6.site-packages.flask_wtf',
              'venv.lib.python3.6.site-packages.flask_wtf.recaptcha', 'venv.lib.python3.6.site-packages.markupsafe',
              'venv.lib.python3.6.site-packages.mongoengine', 'venv.lib.python3.6.site-packages.mongoengine.base',
              'venv.lib.python3.6.site-packages.mongoengine.queryset',
              'venv.lib.python3.6.site-packages.flask_bootstrap', 'venv.lib.python3.6.site-packages.flask_mongoengine',
              'venv.lib.python3.6.site-packages.flask_mongoengine.wtf',
              'venv.lib.python3.6.site-packages.flask_debugtoolbar',
              'venv.lib.python3.6.site-packages.flask_debugtoolbar.panels',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='pavel',
    author_email='',
    description=''
)
